# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adduser.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_adduser(object):
    def setupUi(self, adduser):
        adduser.setObjectName("adduser")
        adduser.resize(334, 337)
        self.pushButton_exit = QtWidgets.QPushButton(adduser)
        self.pushButton_exit.setGeometry(QtCore.QRect(230, 280, 75, 23))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.layoutWidget = QtWidgets.QWidget(adduser)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 40, 135, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.verticalLayout_2.addWidget(self.lineEdit_name)
        self.lineEdit_uname = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_uname.setObjectName("lineEdit_uname")
        self.verticalLayout_2.addWidget(self.lineEdit_uname)
        self.lineEdit_pass = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_pass.setObjectName("lineEdit_pass")
        self.verticalLayout_2.addWidget(self.lineEdit_pass)
        self.lineEdit_retypepass = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_retypepass.setObjectName("lineEdit_retypepass")
        self.verticalLayout_2.addWidget(self.lineEdit_retypepass)
        self.layoutWidget1 = QtWidgets.QWidget(adduser)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 40, 86, 181))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.layoutWidget2 = QtWidgets.QWidget(adduser)
        self.layoutWidget2.setGeometry(QtCore.QRect(33, 240, 141, 22))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.layoutWidget3 = QtWidgets.QWidget(adduser)
        self.layoutWidget3.setGeometry(QtCore.QRect(30, 280, 158, 25))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushinit = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushinit.setObjectName("pushinit")
        self.horizontalLayout_2.addWidget(self.pushinit)
        self.lineEdit_uid = QtWidgets.QLineEdit(adduser)
        self.lineEdit_uid.setEnabled(False)
        self.lineEdit_uid.setGeometry(QtCore.QRect(130, 240, 100, 20))
        self.lineEdit_uid.setObjectName("lineEdit_uid")

        self.retranslateUi(adduser)
        QtCore.QMetaObject.connectSlotsByName(adduser)

    def retranslateUi(self, adduser):
        _translate = QtCore.QCoreApplication.translate
        adduser.setWindowTitle(_translate("adduser", "Add User"))
        self.pushButton_exit.setText(_translate("adduser", "Exit"))
        self.label.setText(_translate("adduser", "Name "))
        self.label_2.setText(_translate("adduser", "User Name"))
        self.label_3.setText(_translate("adduser", "Password"))
        self.label_4.setText(_translate("adduser", "Retype Password"))
        self.label_5.setText(_translate("adduser", "UserID"))
        self.pushinit.setText(_translate("adduser", "Initiate User"))
