# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminlogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_adminlogin(object):
    def setupUi(self, adminlogin):
        adminlogin.setObjectName("adminlogin")
        adminlogin.resize(467, 331)
        self.pushButton_login = QtWidgets.QPushButton(adminlogin)
        self.pushButton_login.setGeometry(QtCore.QRect(230, 290, 80, 24))
        self.pushButton_login.setObjectName("pushButton_login")
        self.label_warn = QtWidgets.QLabel(adminlogin)
        self.label_warn.setGeometry(QtCore.QRect(110, 240, 311, 20))
        self.label_warn.setText("")
        self.label_warn.setObjectName("label_warn")
        self.label_3 = QtWidgets.QLabel(adminlogin)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 161, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton_back = QtWidgets.QPushButton(adminlogin)
        self.pushButton_back.setGeometry(QtCore.QRect(30, 290, 131, 24))
        self.pushButton_back.setObjectName("pushButton_back")
        self.layoutWidget = QtWidgets.QWidget(adminlogin)
        self.layoutWidget.setGeometry(QtCore.QRect(120, 70, 311, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_uname = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_uname.setObjectName("lineEdit_uname")
        self.horizontalLayout.addWidget(self.lineEdit_uname)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_pass = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_pass.setObjectName("lineEdit_pass")
        self.horizontalLayout_2.addWidget(self.lineEdit_pass)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.checkBox_showpass = QtWidgets.QCheckBox(adminlogin)
        self.checkBox_showpass.setGeometry(QtCore.QRect(230, 210, 181, 22))
        self.checkBox_showpass.setObjectName("checkBox_showpass")

        self.retranslateUi(adminlogin)
        QtCore.QMetaObject.connectSlotsByName(adminlogin)

    def retranslateUi(self, adminlogin):
        _translate = QtCore.QCoreApplication.translate
        adminlogin.setWindowTitle(_translate("adminlogin", "Login"))
        self.pushButton_login.setText(_translate("adminlogin", "Login"))
        self.label_3.setText(_translate("adminlogin", "Please enter your credentials"))
        self.pushButton_back.setText(_translate("adminlogin", "Back to Main Menu"))
        self.label.setText(_translate("adminlogin", "Username"))
        self.label_2.setText(_translate("adminlogin", "Password"))
        self.checkBox_showpass.setText(_translate("adminlogin", "Show Password"))
