# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminpanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_adminpanel(object):
    def setupUi(self, adminpanel):
        adminpanel.setObjectName("adminpanel")
        adminpanel.resize(393, 435)
        self.pushButton_logout = QtWidgets.QPushButton(adminpanel)
        self.pushButton_logout.setGeometry(QtCore.QRect(280, 380, 80, 24))
        self.pushButton_logout.setObjectName("pushButton_logout")
        self.layoutWidget = QtWidgets.QWidget(adminpanel)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 70, 231, 291))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_adduser_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_adduser_2.setObjectName("pushButton_adduser_2")
        self.verticalLayout_3.addWidget(self.pushButton_adduser_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_editremove = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_editremove.setObjectName("pushButton_editremove")
        self.verticalLayout_2.addWidget(self.pushButton_editremove)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.label_welcome = QtWidgets.QLabel(adminpanel)
        self.label_welcome.setGeometry(QtCore.QRect(30, 30, 331, 16))
        self.label_welcome.setObjectName("label_welcome")

        self.retranslateUi(adminpanel)
        QtCore.QMetaObject.connectSlotsByName(adminpanel)

    def retranslateUi(self, adminpanel):
        _translate = QtCore.QCoreApplication.translate
        adminpanel.setWindowTitle(_translate("adminpanel", "Admin Panel"))
        self.pushButton_logout.setText(_translate("adminpanel", "Logout"))
        self.pushButton_adduser_2.setText(_translate("adminpanel", "Add User"))
        self.pushButton_editremove.setText(_translate("adminpanel", "Edit/Remove User"))
        self.pushButton_4.setText(_translate("adminpanel", "Manage Repairs"))
        self.pushButton_3.setText(_translate("adminpanel", "Manage Work orders"))
        self.pushButton.setText(_translate("adminpanel", "Manage Labs"))
        self.pushButton_2.setText(_translate("adminpanel", "Report Failure"))
        self.pushButton_5.setText(_translate("adminpanel", "Manage Consumables"))
        self.label_welcome.setText(_translate("adminpanel", " "))
