# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'labmanage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_labmanage(object):
    def setupUi(self, labmanage):
        labmanage.setObjectName("labmanage")
        labmanage.resize(877, 690)
        self.pushButton = QtWidgets.QPushButton(labmanage)
        self.pushButton.setGeometry(QtCore.QRect(50, 70, 141, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(labmanage)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 140, 141, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(labmanage)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 220, 141, 51))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(labmanage)
        QtCore.QMetaObject.connectSlotsByName(labmanage)

    def retranslateUi(self, labmanage):
        _translate = QtCore.QCoreApplication.translate
        labmanage.setWindowTitle(_translate("labmanage", "Manage Labs"))
        self.pushButton.setText(_translate("labmanage", "Add Apparatus"))
        self.pushButton_2.setText(_translate("labmanage", "Edit Apparatus"))
        self.pushButton_3.setText(_translate("labmanage", "Schedule Task"))
