# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(375, 317)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_adminlogin = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_adminlogin.setGeometry(QtCore.QRect(100, 60, 141, 41))
        self.pushButton_adminlogin.setObjectName("pushButton_adminlogin")
        self.pushButton_viewlabs = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_viewlabs.setGeometry(QtCore.QRect(100, 120, 141, 41))
        self.pushButton_viewlabs.setObjectName("pushButton_viewlabs")
        self.pushButton_close = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_close.setGeometry(QtCore.QRect(100, 180, 141, 41))
        self.pushButton_close.setObjectName("pushButton_close")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, -10, 231, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 20, 221, 20))
        self.label_2.setObjectName("label_2")
        self.pushButton_newaccount = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_newaccount.setGeometry(QtCore.QRect(10, 250, 131, 23))
        self.pushButton_newaccount.setObjectName("pushButton_newaccount")
        self.label_logo = QtWidgets.QLabel(self.centralwidget)
        self.label_logo.setGeometry(QtCore.QRect(290, 220, 71, 61))
        self.label_logo.setObjectName("label_logo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 375, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DoME | LRMC"))
        self.pushButton_adminlogin.setText(_translate("MainWindow", "Admin Login"))
        self.pushButton_viewlabs.setText(_translate("MainWindow", "View Labs"))
        self.pushButton_close.setText(_translate("MainWindow", "Exit"))
        self.label.setText(_translate("MainWindow", "Welcome to Lab Resource Management Console"))
        self.label_2.setText(_translate("MainWindow", "Department of Mechanical Engineering"))
        self.pushButton_newaccount.setText(_translate("MainWindow", "Create User Account"))
        self.label_logo.setText(_translate("MainWindow", " "))
