# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'specificfield.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_specificfield(object):
    def setupUi(self, specificfield):
        specificfield.setObjectName("specificfield")
        specificfield.resize(640, 480)
        self.label = QtWidgets.QLabel(specificfield)
        self.label.setGeometry(QtCore.QRect(200, 50, 201, 16))
        self.label.setObjectName("label")
        self.pushButton_back = QtWidgets.QPushButton(specificfield)
        self.pushButton_back.setGeometry(QtCore.QRect(20, 430, 80, 24))
        self.pushButton_back.setObjectName("pushButton_back")
        self.pushButton_6 = QtWidgets.QPushButton(specificfield)
        self.pushButton_6.setGeometry(QtCore.QRect(520, 430, 80, 24))
        self.pushButton_6.setObjectName("pushButton_6")
        self.layoutWidget = QtWidgets.QWidget(specificfield)
        self.layoutWidget.setGeometry(QtCore.QRect(200, 110, 161, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.energy = QtWidgets.QPushButton(self.layoutWidget)
        self.energy.setObjectName("energy")
        self.verticalLayout.addWidget(self.energy)
        self.manuf = QtWidgets.QPushButton(self.layoutWidget)
        self.manuf.setObjectName("manuf")
        self.verticalLayout.addWidget(self.manuf)
        self.autom = QtWidgets.QPushButton(self.layoutWidget)
        self.autom.setObjectName("autom")
        self.verticalLayout.addWidget(self.autom)
        self.other = QtWidgets.QPushButton(self.layoutWidget)
        self.other.setObjectName("other")
        self.verticalLayout.addWidget(self.other)
        self.label_carrier = QtWidgets.QLabel(specificfield)
        self.label_carrier.setGeometry(QtCore.QRect(190, 350, 201, 20))
        self.label_carrier.setText("")
        self.label_carrier.setObjectName("label_carrier")

        self.retranslateUi(specificfield)
        QtCore.QMetaObject.connectSlotsByName(specificfield)

    def retranslateUi(self, specificfield):
        _translate = QtCore.QCoreApplication.translate
        specificfield.setWindowTitle(_translate("specificfield", "Select the Field"))
        self.label.setText(_translate("specificfield", "Please select the specific field"))
        self.pushButton_back.setText(_translate("specificfield", "Back"))
        self.pushButton_6.setText(_translate("specificfield", "Exit"))
        self.energy.setText(_translate("specificfield", "Energy Engineering"))
        self.manuf.setText(_translate("specificfield", "Manufacturing"))
        self.autom.setText(_translate("specificfield", "Automation"))
        self.other.setText(_translate("specificfield", "Other Facilities"))
